### PR TITLE
Adding Clustered Feature Importance Notebook

### PR DESCRIPTION
**Pull request by Harkishan-99**
A new PR for the Clustered Feature Importance Notebook.

### CODE REVIEW

**Comment by Harkishan-99** [comment]
I still don't know why the notebook is not showing up it. Here is the link of the notebook in my forked repo. https://github.com/Harkishan-99/research/blob/master/Chapter8_FeatureImportance/ClusteredFeatureImportance.ipynb

**Comment by Jackal08** [comment]
Hi @Harkishan-99! 

Thanks for this. I have sent you a message on Slack and we can discuss this implementation further. Alex (@proskurin) has a couple of ideas as well.

:)

**Comment by MislavSag** [comment]
I have just check the notebbok. For me, it returns error on this line :


```
#lets generate some synthetic data first
# The dataset will have 10 features ( 2 informative (I), 2 redundent (R) and 4 non-informative (N))
X, cont = get_test_data(n_features=10, n_informative=2, n_redundant=2, n_samples=5000)
X.head(3)
```
The error mesage is :

>  TypeError: __new__() got an unexpected keyword argument 'periods'

It seems the problem is in this part:
`df0 = pd.DatetimeIndex(periods=n_samples, freq=pd.tseries.offsets.Minute(), end=pd.datetime.today())`

pd.DatatimeIndex() deosn't have periods argument (at least in pandas 1.0.3.)

**Comment by Harkishan-99** [comment]
Hi @MislavSag this PR is outdated. I am developing a new notebook and will PR it after the merging of CFI feature is completed in the mlfinlab repo. Please don't bother to use this notebook.

**Comment by MislavSag** [comment]
@Harkishan-99 , ok, thanks for the feedback. Is there a development version od cluster importance in mlfinlab?

**Comment by Harkishan-99** [comment]
This PR might help https://github.com/hudson-and-thames/mlfinlab/pull/242

**Pull request closed without merging**
