### PR TITLE
Open-source soldier of fortune

### PR DESCRIPTION
**Pull request by mirca**
Hello everyone,

here is my submission for #101 

Looking forward to hearing from you.

Best.

### CODE REVIEW

**Comment by aditya1702** [comment]
@mirca Thank you for the submission. We will review it and get back to you soon!

**Comment by Jackal08** [comment]
Hi @mirca, 

You certainly have our attention. Are you on the slack channel and we can discuss this further?

Are you currently in Hong Kong time zone? GMT+8

**Comment by mirca** [comment]
Thank you all for the feedback on slack!

**Comment by Jackal08** [comment]
Brilliant notebook. Thanks @mirca !

**Pull request merged**
